# Generated by Django 2.2.12 on 2020-05-20 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('address', djongo.models.fields.EmbeddedField(model_container=home.models.Address, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('surname', models.CharField(max_length=254)),
                ('current_cvs', djongo.models.fields.ArrayField(model_container=home.models.Cv)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
